/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import  Modelos.Camioneta;
import Modelos.Auto;
import Modelos.Cliente;
import Modelos.Venta;
import java.util.ArrayList;
import Modelos.Vehiculo;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author joako
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Auto auxAuto= new Auto();
        ArrayList<Vehiculo> vehiculos= new ArrayList<>();
    public Principal() {
        initComponents();
        panelArriba.removeAll();
        contenedor.remove(cargaAuto);
        contenedor.remove(Cvehi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelAzul = new javax.swing.JPanel();
        botonVehi = new javax.swing.JLabel();
        botonVent = new javax.swing.JLabel();
        panelArriba = new javax.swing.JPanel();
        consultaVehi = new javax.swing.JLabel();
        CargaVehi = new javax.swing.JLabel();
        eliminaVehi = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        cargaAuto = new javax.swing.JPanel();
        cNChasis = new javax.swing.JLabel();
        iCNChasis = new javax.swing.JTextField();
        iCNMotor = new javax.swing.JTextField();
        cNMotor = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Inicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Cvehi = new javax.swing.JPanel();
        cargaAutob = new javax.swing.JLabel();
        cargaCamionetab = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAzul.setBackground(new java.awt.Color(0, 153, 255));

        botonVehi.setBackground(new java.awt.Color(0, 153, 255));
        botonVehi.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonVehi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonVehi.setText("VEHICULOS");
        botonVehi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVehi.setOpaque(true);
        botonVehi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonVehiMouseMoved(evt);
            }
        });
        botonVehi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVehiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVehiMousePressed(evt);
            }
        });

        botonVent.setBackground(new java.awt.Color(0, 153, 255));
        botonVent.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonVent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonVent.setText("VENTAS");
        botonVent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVent.setOpaque(true);
        botonVent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonVentMouseMoved(evt);
            }
        });
        botonVent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVentMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVehi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
            .addComponent(botonVent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(botonVehi)
                .addGap(37, 37, 37)
                .addComponent(botonVent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelArriba.setBackground(new java.awt.Color(204, 204, 204));

        consultaVehi.setText("Consultar Vehiculo");
        consultaVehi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CargaVehi.setText("Cargar Vehiculo");
        CargaVehi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargaVehi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CargaVehiMousePressed(evt);
            }
        });

        eliminaVehi.setText("Eliminar Vehiculo");
        eliminaVehi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelArribaLayout = new javax.swing.GroupLayout(panelArriba);
        panelArriba.setLayout(panelArribaLayout);
        panelArribaLayout.setHorizontalGroup(
            panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArribaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(CargaVehi)
                .addGap(118, 118, 118)
                .addComponent(eliminaVehi)
                .addGap(122, 122, 122)
                .addComponent(consultaVehi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelArribaLayout.setVerticalGroup(
            panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArribaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaVehi)
                    .addComponent(CargaVehi)
                    .addComponent(eliminaVehi))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setLayout(new java.awt.CardLayout());

        cNChasis.setText("N° chasis");

        iCNChasis.setBackground(new java.awt.Color(153, 153, 153));
        iCNChasis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCNChasisActionPerformed(evt);
            }
        });

        iCNMotor.setBackground(new java.awt.Color(153, 153, 153));
        iCNMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCNMotorActionPerformed(evt);
            }
        });

        cNMotor.setText("N° motor");

        jTextField3.setBackground(new java.awt.Color(153, 153, 153));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Año");

        jTextField4.setBackground(new java.awt.Color(153, 153, 153));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca");

        jTextField5.setBackground(new java.awt.Color(153, 153, 153));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Modelo");

        jLabel8.setText("Color");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Gris", "Amarillo", "Azul", "Rojo", "Verde", "Marron", "Naranja" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 153, 0));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Confirmar");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel1.setText("N° puertas");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cargaAutoLayout = new javax.swing.GroupLayout(cargaAuto);
        cargaAuto.setLayout(cargaAutoLayout);
        cargaAutoLayout.setHorizontalGroup(
            cargaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargaAutoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(cargaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(cNMotor)
                    .addComponent(iCNMotor, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(cNChasis)
                    .addComponent(iCNChasis)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(652, Short.MAX_VALUE))
        );
        cargaAutoLayout.setVerticalGroup(
            cargaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargaAutoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cNChasis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iCNChasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cNMotor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iCNMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
        );

        contenedor.add(cargaAuto, "card4");

        jLabel3.setText("Bienvenido");

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel3)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel3)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        contenedor.add(Inicio, "card2");

        cargaAutob.setText("Auto");
        cargaAutob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cargaAutobMousePressed(evt);
            }
        });

        cargaCamionetab.setText("Camioneta");

        javax.swing.GroupLayout CvehiLayout = new javax.swing.GroupLayout(Cvehi);
        Cvehi.setLayout(CvehiLayout);
        CvehiLayout.setHorizontalGroup(
            CvehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CvehiLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(cargaAutob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(cargaCamionetab)
                .addGap(243, 243, 243))
        );
        CvehiLayout.setVerticalGroup(
            CvehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CvehiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CvehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargaAutob)
                    .addComponent(cargaCamionetab))
                .addContainerGap(509, Short.MAX_VALUE))
        );

        contenedor.add(Cvehi, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelAzul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVehiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVehiMousePressed
        panelArriba.add(CargaVehi);
        panelArriba.add(eliminaVehi);
        panelArriba.add(consultaVehi);
        contenedor.removeAll();
        contenedor.add(Inicio);
        panelArriba.repaint();
    }//GEN-LAST:event_botonVehiMousePressed

    private void CargaVehiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargaVehiMousePressed
        // TODO add your handling code here:
        contenedor.add(Cvehi);
        contenedor.remove(Inicio);
        contenedor.repaint();
        

    }//GEN-LAST:event_CargaVehiMousePressed

    private void cargaAutobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargaAutobMousePressed
        // TODO add your handling code here:
        contenedor.add(cargaAuto);
        contenedor.remove(Cvehi);
        contenedor.repaint();
    }//GEN-LAST:event_cargaAutobMousePressed

    private void iCNChasisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCNChasisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCNChasisActionPerformed

    private void iCNMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCNMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCNMotorActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        int aux = Integer.parseInt(iCNChasis.getText());
        auxAuto.setNroChasis(aux);
        //Terminar De cargar todos los datos
        vehiculos.add(auxAuto);
        contenedor.add(Inicio);
        contenedor.remove(cargaAuto);
        contenedor.repaint();
        
    }//GEN-LAST:event_jLabel9MousePressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void botonVehiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVehiMouseMoved
        setLabelBackgroundBlue(botonVehi);
    }//GEN-LAST:event_botonVehiMouseMoved

    private void botonVentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentMouseMoved
        setLabelBackgroundBlue(botonVent);
    }//GEN-LAST:event_botonVentMouseMoved

    private void botonVehiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVehiMouseExited
        resetLabelBackgroundBlue(botonVehi);
    }//GEN-LAST:event_botonVehiMouseExited

    private void botonVentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentMouseExited
        resetLabelBackgroundBlue(botonVent);
    }//GEN-LAST:event_botonVentMouseExited

       public void setLabelBackgroundBlue(JLabel j1){
        j1.setBackground(new Color(0, 0, 255));
    }
    
    public void resetLabelBackgroundBlue(JLabel j1){
        j1.setBackground(new Color(0, 153, 255));
    }
    
    public void setLabelBackgroundGrey(JLabel j1){
        j1.setBackground(new Color(170, 170, 170));
    }
    
    public void resetLabelBackgroundGrey(JLabel j1){
        j1.setBackground(new Color(204, 204, 204));
        
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CargaVehi;
    private javax.swing.JPanel Cvehi;
    private javax.swing.JPanel Inicio;
    private javax.swing.JLabel botonVehi;
    private javax.swing.JLabel botonVent;
    private javax.swing.JLabel cNChasis;
    private javax.swing.JLabel cNMotor;
    private javax.swing.JPanel cargaAuto;
    private javax.swing.JLabel cargaAutob;
    private javax.swing.JLabel cargaCamionetab;
    private javax.swing.JLabel consultaVehi;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel eliminaVehi;
    private javax.swing.JTextField iCNChasis;
    private javax.swing.JTextField iCNMotor;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel panelArriba;
    private javax.swing.JPanel panelAzul;
    // End of variables declaration//GEN-END:variables
}
